#spring:
#  datasource:
#    url: jdbc:mysql://192.168.0.250:3306/zjyzv1?useUnicode=true&characterEncoding=utf8
#    driver: com.mysql.jdbc.Driver
#    username: zjyzpre
#    password: Zjyz@zjyzpre#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zjyz.fx.entity
#  configuration:
#    map-underscore-to-camel-case: true
